{% set name = "open3spn2" %}
{% set version = "0.3.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/cabb99/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 549f4023e313af0a7c51e6427cf1612cb3e6afb13d2fac704db0de88622dd812

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
  run:
    - biopython
    - numpy
    - openmm
    - pandas
    - pdbfixer
    - scipy

test:
  imports:
    - open3SPN2

about:
  home: https://github.com/cabb99/open3spn2
  summary: 'Implementation of 3SPN2 and 3SPN2.C forcefields in OpenMM'
  description: "An Implementation of the 3SPN.2 and 3SPN.2C coarse-grained molecular model of DNA in OpenMM."
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://open3spn2.readthedocs.io/en/latest/
  dev_url: https://github.com/cabb99/open3spn2

extra:
  recipe-maintainers:
    - cabb99