package:
  name: "open3spn2"
  version: "0.2.0"

source:
  git_url: https://github.com/cabb99/open3spn2.git
  git_rev: 0.2.0
  git_depth: -1 # (Defaults to -1/not shallow)

build:
  noarch: python
  number: 0
  script: python setup.py install --record=record.txt

requirements:
  host:
    - pip
    - python
  run:
    - python
    - biopython
    - mdtraj
    - nose
    - numpy
    - openmm
    - pandas
    - scipy
    - pdbfixer

test:
  imports:
    - open3SPN2

about:
  home: "https://github.com/cabb99/open3spn2"
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Implementation of 3SPN2 and 3SPN2.C forcefields in openmm"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - cabb99
